import { pgTable, text, timestamp, real, boolean, jsonb, serial } from 'drizzle-orm/pg-core';

export const reps = pgTable('reps', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  teamCode: text('team_code').default(''),
  role: text('role').default('rep'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const properties = pgTable('properties', {
  id: text('id').primaryKey(),
  locationLabel: text('location_label').notNull(),
  lat: real('lat').notNull(),
  lng: real('lng').notNull(),
  resultType: text('result_type').default('address'),
  radiusMiles: real('radius_miles').default(20),
  historyPreset: text('history_preset').default('1y'),
  sinceDate: text('since_date'),
  stormDateCount: real('storm_date_count').default(0),
  latestStormDate: text('latest_storm_date'),
  latestMaxHailInches: real('latest_max_hail_inches').default(0),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const leads = pgTable('leads', {
  id: text('id').primaryKey(),
  propertyLabel: text('property_label').notNull(),
  stormDate: text('storm_date').notNull(),
  stormLabel: text('storm_label').notNull(),
  lat: real('lat').notNull(),
  lng: real('lng').notNull(),
  locationLabel: text('location_label').notNull(),
  sourceEventId: text('source_event_id'),
  sourceLabel: text('source_label').default(''),
  topHailInches: real('top_hail_inches').default(0),
  reportCount: real('report_count').default(0),
  evidenceCount: real('evidence_count').default(0),
  priority: text('priority').default('Monitor'),
  status: text('status').default('queued'),
  outcome: text('outcome').default('none'),
  leadStage: text('lead_stage').default('new'),
  notes: text('notes').default(''),
  reminderAt: text('reminder_at'),
  assignedRep: text('assigned_rep').default(''),
  dealValue: real('deal_value'),
  stageHistory: jsonb('stage_history').default([]),
  homeownerName: text('homeowner_name').default(''),
  homeownerPhone: text('homeowner_phone').default(''),
  homeownerEmail: text('homeowner_email').default(''),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  visitedAt: timestamp('visited_at'),
  completedAt: timestamp('completed_at'),
});

export const evidence = pgTable('evidence', {
  id: text('id').primaryKey(),
  kind: text('kind').notNull(),
  provider: text('provider').notNull(),
  mediaType: text('media_type').notNull(),
  propertyLabel: text('property_label').notNull(),
  stormDate: text('storm_date'),
  title: text('title').notNull(),
  notes: text('notes'),
  externalUrl: text('external_url'),
  thumbnailUrl: text('thumbnail_url'),
  publishedAt: text('published_at'),
  fileName: text('file_name'),
  mimeType: text('mime_type'),
  sizeBytes: real('size_bytes'),
  status: text('status').default('pending'),
  includeInReport: boolean('include_in_report').default(false),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const archives = pgTable('archives', {
  id: text('id').primaryKey(),
  propertyLabel: text('property_label').notNull(),
  summaryLabel: text('summary_label').notNull(),
  stops: jsonb('stops').default([]),
  createdAt: timestamp('created_at').defaultNow(),
  archivedAt: timestamp('archived_at').defaultNow(),
});

export const shareableReports = pgTable('shareable_reports', {
  id: serial('id').primaryKey(),
  slug: text('slug').notNull().unique(),
  address: text('address').notNull(),
  lat: real('lat').notNull(),
  lng: real('lng').notNull(),
  stormDate: text('storm_date').notNull(),
  stormLabel: text('storm_label').notNull(),
  maxHailInches: real('max_hail_inches').default(0),
  maxWindMph: real('max_wind_mph').default(0),
  eventCount: real('event_count').default(0),
  repName: text('rep_name'),
  repPhone: text('rep_phone'),
  companyName: text('company_name'),
  homeownerName: text('homeowner_name'),
  createdAt: timestamp('created_at').defaultNow(),
  expiresAt: timestamp('expires_at'),
});
